# Generated by Django 3.0 on 2019-12-20 20:51

import alumnos.validacion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_auto_20191220_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nota1',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[alumnos.validacion.valor_nota]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nota2',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[alumnos.validacion.valor_nota]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nota3',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[alumnos.validacion.valor_nota]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nota4',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[alumnos.validacion.valor_nota]),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='promedio',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
